### ISSUE TITLE
Emeralds

### ISSUE THREAD

**Issue by DEVensiv** [OneDayStudios/StargateMC-Public#21]
**Describe the bug**
No Emerald oregen on some Planets

**To Reproduce**
1. Come on O3OLYAO0 and fly around with a digital miner yourself for 2h and get that there are no emeralds

**Expected behavior**
Like in a normal mc world you have 2-5 emerald ore in 1 fullrange digimier

**Screenshots**
screenshot not possible for that bug

**Versions (please complete the following information):**
 - Beta18
 - to countercheck a little self written unstable mod to check if a block is contained in the area

**Additional context**
Additional the village spawn is way to low (not one village on this planet)

**Comment by Bysokar** [comment]
Hi @Devensiv,

This is to be expected... emerald is quite rare and more often found in mountain biomes.
 It is possible you will have to travel offworld to obtain resources in some circumstances.

Let me know if any recipes for warpdrive or basic stargate tech require emeralds and we will look at changing them.. otherwise please explore more than just your world.

Regards

Bysokar
